#ifndef FONTS_H
#define FONTS_H

#define FONT_SIZE 5

// Letter Fonts
static const int A[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,0},
    {1,0,0,0,1},
    {1,1,1,1,1},
    {1,0,0,0,1},
    {1,0,0,0,1}};
static const int B[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,1},
    {1,1,1,1,0},
    {1,0,0,0,1},
    {1,1,1,1,1}};
static const int C[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,0},
    {1,0,0,0,0},
    {1,0,0,0,0},
    {1,1,1,1,1}};
static const int D[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,0},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,1,1,1,0}};
static const int E[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,0},
    {1,1,1,1,1},
    {1,0,0,0,0},
    {1,1,1,1,1}};
static const int F[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,0},
    {1,1,1,1,0},
    {1,0,0,0,0},
    {1,0,0,0,0}};
static const int G[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,0},
    {1,0,1,1,1},
    {1,0,0,0,1},
    {1,1,1,1,1}};
static const int H[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,1,1,1,1},
    {1,0,0,0,1},
    {1,0,0,0,1}};
static const int I[FONT_SIZE][FONT_SIZE] = {
    {0,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0}};
static const int J[FONT_SIZE][FONT_SIZE] = {
    {0,0,0,0,1},
    {0,0,0,0,1},
    {0,0,0,0,1},
    {1,0,0,0,1},
    {1,1,1,1,1}};
static const int K[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,1,0},
    {1,1,1,0,0},
    {1,0,0,1,0},
    {1,0,0,0,1}};
static const int L[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,0},
    {1,0,0,0,0},
    {1,0,0,0,0},
    {1,0,0,0,0},
    {1,1,1,1,1}};
static const int M[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,1,0,1,1},
    {1,0,1,0,1},
    {1,0,1,0,1},
    {1,0,0,0,1}};
static const int N[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,1,0,0,1},
    {1,0,1,0,1},
    {1,0,0,1,1},
    {1,0,0,0,1}};
static const int O[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,1,1,1,1}};
static const int Q[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,1,1,1,1},
    {0,0,0,1,0}};
static const int P[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,0},
    {1,0,0,0,1},
    {1,1,1,1,0},
    {1,0,0,0,0},
    {1,0,0,0,0}};
static const int R[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,0},
    {1,0,0,0,1},
    {1,1,1,1,0},
    {1,0,0,0,1},
    {1,0,0,0,1}};
static const int S[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {1,0,0,0,0},
    {1,1,1,1,1},
    {0,0,0,0,1},
    {1,1,1,1,1}};
static const int T[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {0,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0}};
static const int U[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {0,1,1,1,0}};
static const int V[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,0,1},
    {0,1,0,1,0},
    {0,1,0,1,0},
    {0,0,1,0,0}};
static const int W[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,0,1,0,1},
    {1,0,1,0,1},
    {0,1,1,1,0}};
static const int X[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {0,1,0,1,0},
    {0,0,1,0,0},
    {0,1,0,1,0},
    {1,0,0,0,1}};
static const int Y[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,0,1},
    {0,1,0,1,0},
    {0,0,1,0,0},
    {0,0,1,0,0}};
static const int Z[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {0,0,0,1,0},
    {0,0,1,0,0},
    {0,1,0,0,0},
    {1,1,1,1,1}};                                           

// Digit Fonts
static const int NUM0[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,0},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,0,0,0,1},
    {0,1,1,1,0}};  
static const int NUM1[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,0,0},
    {1,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0},
    {0,0,1,0,0}};
static const int NUM2[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,0},
    {1,0,0,0,1},
    {0,0,0,1,0},
    {0,0,1,0,0},
    {1,1,1,1,1}};
static const int NUM3[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,0},
    {0,0,0,0,1},
    {0,1,1,1,0},
    {0,0,0,0,1},
    {1,1,1,1,0}};
static const int NUM4[FONT_SIZE][FONT_SIZE] = {
    {1,0,0,0,1},
    {1,0,0,0,1},
    {1,1,1,1,1},
    {0,0,0,0,1},
    {0,0,0,0,1}};
static const int NUM5[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,1},
    {1,0,0,0,0},
    {0,1,1,1,1},
    {0,0,0,0,1},
    {1,1,1,1,1}};
static const int NUM6[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,1},
    {1,0,0,0,0},
    {1,1,1,1,0},
    {1,0,0,0,1},
    {0,1,1,1,0}};
static const int NUM7[FONT_SIZE][FONT_SIZE] = {
    {1,1,1,1,1},
    {0,0,0,0,1},
    {0,0,0,1,0},
    {0,0,1,0,0},
    {0,1,0,0,0}};          
static const int NUM8[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,0},
    {1,0,0,0,1},
    {0,1,1,1,0},
    {1,0,0,0,1},
    {0,1,1,1,0}};
static const int NUM9[FONT_SIZE][FONT_SIZE] = {
    {0,1,1,1,0},
    {1,0,0,0,1},
    {0,1,1,1,1},
    {0,0,0,1,0},
    {0,0,1,0,0}};
static const int COLON[FONT_SIZE][FONT_SIZE] = {
    {1,1,0,0,0},
    {1,1,0,0,0},
    {0,0,0,0,0},
    {1,1,0,0,0},
    {1,1,0,0,0}};
static const int SPACE[FONT_SIZE][FONT_SIZE] = {
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0}};   

// Ascii Fonts Table
static const int (*asciiFontTable[91])[FONT_SIZE][FONT_SIZE] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,&SPACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    &NUM0, &NUM1, &NUM2, &NUM3, &NUM4, &NUM5, &NUM6, &NUM7, &NUM8, &NUM9, &COLON,0,0,0,0,0,0,&A, &B, &C,
    &D, &E, &F, &G, &H, &I, &J, &K, &L, &M, &N, &O, &P, &Q, &R, &S, &T, &U, &V, &W, &X, &Y, &Z};                                                                       

#endif